Added XML and HTML report

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,3 +29,10 @@ jobs:
         run: pipenv run install-playwright-dependencies
       - name: Run e2e-tests
         run: pipenv run e2e-tests
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Pytest Report            # Name of the check run which will be created
+          path: test-report/report.xml    # Path to test results
+          reporter: jest-junit        # Format of test results
